version: "3.4"
services:
 vite:
   image: node:alpine
   container_name: vue
   entrypoint: /bin/sh
   ports:
     - 3000:3000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true